backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow # simple | editorial_workflow
local_backend: true
media_folder: static/img
public_folder: /img

display_url: http://localhost:8000
# logo_url: src/img/logo_500.jpg

collections:
  - name: "pages"
    label: "Pages"
    files:

      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string, required: false },
                  { label: Image, name: image, widget: image },
                  { label: CTA Button Text, name: cta_btn_text, widget: string, required: false },
                  { label: CTA Button Link, name: cta_btn_link, widget: string, required: false },
                ],
            }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Enabled, name: enabled, widget: boolean, default: true, required: false },
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Features,
                    name: features,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                        { label: Description, name: description, widget: text, required: false },
                      ],
                  }
                ],
            }

          - {
              label: Retreats,
              name: retreats,
              widget: object,
              fields:
                [
                  { label: Enabled, name: enabled, widget: boolean, default: true },
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: CTA Button Text, name: cta_btn_text, widget: string }
                ],
            }

          - {
            label: About,
            name: about,
            widget: object,
            fields:
              [
                { label: Enabled, name: enabled, widget: boolean, default: true },
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                { label: Image, name: image, widget: image },
                { label: CTA Button Text, name: cta_btn_text, widget: string },
                { label: CTA Button Link, name: cta_btn_link, widget: string },
              ],
            }
          
          - {
            label: Corporate Wellness,
            name: corporate,
            widget: object,
            fields:
              [
                { label: Enabled, name: enabled, widget: boolean, default: true },
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                { label: CTA Button Text, name: cta_btn_text, widget: string },
                { label: CTA Button Link, name: cta_btn_link, widget: string },
              ],
            }

          - {
            label: Reviews,
            name: reviews,
            widget: object,
            fields:
              [
                { label: Enabled, name: enabled, widget: boolean, default: true },
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                {
                  label: Reviews,
                  name: reviews,
                  widget: list,
                  fields:
                    [
                      { label: Name, name: name, widget: string },
                      { label: Quote, name: quote, widget: text },
                      { label: Image, name: image, widget: image },
                    ],
                }
              ],
            }

          - {
              label: Show Blog,
              name: showBlog,
              widget: boolean,
              default: true,
              required: false
            }

      - file: "src/pages/retreats/index.md"
        label: "Retreats"
        name: "retreats"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "retreats-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }

      - file: "src/pages/training/index.md"
        label: "In-Person Training"
        name: "training"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "training-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/coaching/index.md"
        label: "Online Coaching"
        name: "coaching"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "coaching-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - file: "src/pages/programs/index.md"
        label: "Ready-Made Programs"
        name: "programs"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "programs-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "retreat"
    label: "Retreat"
    folder: "src/pages/retreat"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "retreat-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Location", name: "location", widget: "map" }
      - { 
          label: "Price", 
          name: "price", 
          widget: "number",
          value_type: "float",
          decimals: 2
        }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/config/globalSettings.md"
        label: "Global Settings"
        name: "settings"
        editor:
          preview: false
        fields:
        - { label: Site Title, name: title, widget: string, default: 'Not Your Guru' }
        - { label: Site Logo, name: logo, widget: image }
        - { label: Site Accent Color, name: color, widget: color }
        - { 
          label: Menu Items, 
          name: menu, 
          collapsed: true,
          hint: Use this menu to enable/disable menu items from the site's navbar,
          widget: object, 
          fields: [
            { label: Training, name: training, widget: boolean },
            { label: Coaching, name: coaching, widget: boolean },
            { label: Ready-Made Programs, name: programs, widget: boolean },
            { label: Blog, name: blog, widget: boolean },
          ] 
        }