backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow # simple | editorial_workflow
local_backend: true
media_folder: static/img
public_folder: /img

display_url: http://localhost:8000
# logo_url: src/img/logo_500.jpg

collections:
  - name: "pages"
    label: "Pages"
    files:

      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string, required: false },
                  { label: Image, name: image, widget: image },
                  { label: CTA Button Text, name: cta_btn_text, widget: string, required: false },
                  { label: CTA Button Link, name: cta_btn_link, widget: string, required: false },
                ],
            }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Enabled, name: enabled, widget: boolean, default: true, required: false },
                  { label: Heading, name: heading, widget: string },
                  { label: Centered, name: centered, widget: boolean, default: true },
                  { label: Description, name: description, widget: text, required: false },
                  {
                    label: Features,
                    name: features,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: string },
                        { label: Description, name: description, widget: text, required: false },
                      ],
                  }
                ],
            }

          - {
              label: Retreats,
              name: retreats,
              widget: object,
              fields:
                [
                  { label: Enabled, name: enabled, widget: boolean, default: true },
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: CTA Button Text, name: cta_btn_text, widget: string }
                ],
            }

          - {
            label: About,
            name: about,
            widget: object,
            fields:
              [
                { label: Enabled, name: enabled, widget: boolean, default: true },
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                { label: Image, name: image, widget: image },
                { label: CTA Button Text, name: cta_btn_text, widget: string },
                { label: CTA Button Link, name: cta_btn_link, widget: string },
              ],
            }
          
          - {
            label: Corporate Wellness,
            name: corporate,
            widget: object,
            fields:
              [
                { label: Enabled, name: enabled, widget: boolean, default: true },
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                { label: CTA Button Text, name: cta_btn_text, widget: string },
                { label: CTA Button Link, name: cta_btn_link, widget: string },
              ],
            }

          - {
            label: Reviews,
            name: reviews,
            widget: object,
            fields:
              [
                { label: Enabled, name: enabled, widget: boolean, default: true },
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                {
                  label: Reviews,
                  name: reviews,
                  widget: list,
                  fields:
                    [
                      { label: Name, name: name, widget: string },
                      { label: Quote, name: quote, widget: text },
                      { label: Image, name: image, widget: image },
                    ],
                }
              ],
            }

          - {
              label: Show Blog,
              name: showBlog,
              widget: boolean,
              default: true,
              required: false
            }

      - file: "src/pages/retreats/index.md"
        label: "Retreats Page"
        name: "retreats"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "retreats-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string, required: false }
          # - { label: Description, name: description, widget: string, required: false }
          - { label: Body, name: body, widget: markdown, required: false }
          # - {
          #     label: Intro,
          #     name: intro,
          #     widget: object,
          #     fields:
          #       [
          #         { label: Heading, name: heading, widget: string },
          #         { label: Description, name: description, widget: text },
          #         {
          #           label: Blurbs,
          #           name: blurbs,
          #           widget: list,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Text, name: text, widget: text },
          #             ],
          #         },
          #       ],
          #   }
          # - {
          #     label: Main,
          #     name: main,
          #     widget: object,
          #     fields:
          #       [
          #         { label: Heading, name: heading, widget: string },
          #         { label: Description, name: description, widget: text },
          #         {
          #           label: Image1,
          #           name: image1,
          #           widget: object,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Alt, name: alt, widget: string },
          #             ],
          #         },
          #         {
          #           label: Image2,
          #           name: image2,
          #           widget: object,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Alt, name: alt, widget: string },
          #             ],
          #         },
          #         {
          #           label: Image3,
          #           name: image3,
          #           widget: object,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Alt, name: alt, widget: string },
          #             ],
          #         },
          #       ],
          #   }
          # - {
          #     label: Testimonials,
          #     name: testimonials,
          #     widget: list,
          #     fields:
          #       [
          #         { label: Quote, name: quote, widget: string },
          #         { label: Author, name: author, widget: string },
          #       ],
          #   }
          # - { label: Full_image, name: full_image, widget: image }
          # - {
          #     label: Pricing,
          #     name: pricing,
          #     widget: object,
          #     fields:
          #       [
          #         { label: Heading, name: heading, widget: string },
          #         { label: Description, name: description, widget: string },
          #         {
          #           label: Plans,
          #           name: plans,
          #           widget: list,
          #           fields:
          #             [
          #               { label: Plan, name: plan, widget: string },
          #               { label: Price, name: price, widget: string },
          #               {
          #                 label: Description,
          #                 name: description,
          #                 widget: string,
          #               },
          #               { label: Items, name: items, widget: list },
          #             ],
          #         },
          #       ],
          #   }

      - file: "src/pages/training/index.md"
        label: "In-Person Training"
        name: "training"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "training-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/coaching/index.md"
        label: "Online Coaching"
        name: "coaching"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "coaching-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - file: "src/pages/programs/index.md"
        label: "Ready-Made Programs"
        name: "programs"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "programs-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Image, name: image, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "retreat"
    label: "Retreats"
    label_singular: "Retreat"
    folder: "src/pages/retreat"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "retreat-post",
        }
      - { label: "Title", name: "title", widget: "string", hint: The display name for the event }
      - { label: "Subtitle", name: "subtitle", widget: "string", hint: A short teaser for the retreat. Shows up in colored text below image on retreat preview tiles }
      - { label: "Description", name: "description", widget: "text", hint: A short text description of the retreat that shows up in the retreat previews }
      - { label: "Start Date", name: "startDate", widget: "datetime", hint: The starting date for the event (also used for ordering events)}
      - { label: "End Date", name: "endDate", widget: "datetime", hint: The ending date for the event }
      - { label: "Featured", name: "featuredRetreat", widget: "boolean", hint: 'A "featured" event could be highlighted or placed more prominently on the site (not active)' }
      - { label: "Sold Out", name: "soldOut", widget: "boolean", required: false, hint: Check if sold out and retreat will display as sold out (not implemented)' }
      - { label: "Featured Image", name: "featuredimage", widget: image, hint: The image associated with the retreat }
      - { 
          label: "Price", 
          name: "price", 
          widget: "number",
          value_type: "float",
          decimals: 2,
          hint: The cost of the retreat in dollars
        }
      - { label: "Body", name: "body", widget: "markdown", hint: This is the main area where you can put whatever you want about the retreat. Supports text formatting, images, links, etc. Make it as long as you want. }
      - { label: "Location", name: "location", widget: "map", hint: Add the event location on the map }
      - { label: "Tags", name: "tags", widget: "list", hint: "Add any text tags you would like this event organized under. For example if you had two types of retreats, some in NY and some in CR, you coudld use tags to keeps things organized. If you added the CR tag to all CR retreats, one could click on the CR tag to see a filtered list on just retreats in CR."  }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/config/globalSettings.md"
        label: "Global Settings"
        name: "settings"
        editor:
          preview: false
        fields:
        - { 
            label: Site Title, 
            name: title, 
            widget: string, 
            default: 'Not Your Guru', 
            hint: 'Shows up in various places on the site. Header, Footer, etc.' 
          }
        - { 
            label: Site Logo, 
            name: logo, 
            widget: image, 
            hint: This will change the logo in the top navbar and the site footer 
          }
        # - { label: Site Accent Color (not active), name: color, widget: color }
        - { 
          label: Menu Items, 
          name: menu, 
          collapsed: true,
          hint: Enable/disable menu items from the site's main navigation (top header and footer menus),
          widget: object, 
          fields: [
            {
              # using this hidden attribute to help with finding it via graphql queries
              label: Usage,
              name: usage,
              widget: hidden,
              default: settings,
            },
            { label: Home, name: home, widget: boolean },
            { label: Training, name: training, widget: boolean },
            { label: Coaching, name: coaching, widget: boolean },
            { label: Ready-Made Programs, name: programs, widget: boolean },
            { label: Blog, name: blog, widget: boolean },
          ] 
        }
        - { 
          label: Socials (footer), 
          name: socials, 
          collapsed: true,
          hint: Social media links in the site footer,
          widget: object, 
          fields: [
            { 
              label: Facebook, 
              name: facebook, 
              widget: object, 
              fields: 
                [
                  { label: Link, name: link, widget: string },
                  { label: Enabled, name: enabled, widget: boolean },
                ] 
            },
            { 
              label: X, 
              name: x, 
              widget: object, 
              fields: 
                [
                  { label: Link, name: link, widget: string },
                  { label: Enabled, name: enabled, widget: boolean },
                ] 
            },
            { 
              label: Instagram, 
              name: instagram, 
              widget: object, 
              fields: 
                [
                  { label: Link, name: link, widget: string },
                  { label: Enabled, name: enabled, widget: boolean },
                ] 
            },
            { 
              label: YouTube, 
              name: youtube, 
              widget: object, 
              fields: 
                [
                  { label: Link, name: link, widget: string },
                  { label: Enabled, name: enabled, widget: boolean },
                ] 
            },
          ] 
        }